version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - pip install pdm
    post_install:
      - pdm use -f $READTHEDOCS_VIRTUALENV_PATH
      - pdm install -G doc

sphinx:
  configuration: doc/conf.py
