# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: fluiddyn/python-stable
options:
  max-time: 10
pipelines:
  branches:
    default:
      - parallel:
        - step:
            image: fluiddyn/python3-stable
            caches:
              - pip
            script:
              - pip install -U tox --user
              - tox -e py36,codecov
        - step:
            image: fluiddyn/python3-stable
            caches:
              - pip
            script:
              - pip install -U tox --user
              - tox -vv -e py36-pythran,codecov
    dev:
      - parallel:
        - step:
            image: fluiddyn/python3-stable
            caches:
              - pip
            script:
              - pip install -U tox --user
              - tox -e py36,codecov
        - step:
            image: fluiddyn/python3-stable
            caches:
              - pip
            script:
              - pip install -U tox --user
              - tox -vv -e py36-pythran,codecov
