[project]
name = "transonic"
version = "0.1.0"
description = "Add a short description here"
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]

[tasks]
# use as `pixi run install-editable`
install-dependencies = "pixi install && pip install -e ./_transonic_testing"
install-editable = {cmd = "pip install -e . -v --no-deps", depends_on = ["install-dependencies"]}

[dependencies]
beniget = ">=0.4.1,<0.5"
autopep8 = ">=2.0.4"
gast = ">=0.5.4,<0.6"
numpy = ">=1.26.3"
nbval = ">=0.10.0,<0.11"
scipy = ">=1.11.4,<1.12"
pytest = ">=7.4.4,<7.5"
pytest-cov = ">=4.1.0,<4.2"
coverage = ">=7.4.0,<7.5"
black = ">=23.12.1,<23.13"
mpi4py = ">=3.1.5,<3.2"
pip = ">=23.3.2,<23.4"
numba = ">=0.58.1,<0.59"
cython = ">=3.0.7,<3.1"
pythran = ">=0.15.0,<0.16"

[build-dependencies]
pdm-backend = ">=2.1.8,<2.2"

[pypi-dependencies]
pytest-venv = "*"
