[project]
name = "transonic"
version = "0.1.0"
description = "Make your Python code fly at transonic speeds!"
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]

[tasks]
# use as `pixi run install-editable`
install-dependencies = "pixi install && pip install -e ./_transonic_testing"
install-editable = {cmd = "pip install -e . -v --no-deps", depends-on = ["install-dependencies"]}

[dependencies]
beniget = ">=0.4.1"
autopep8 = ">=2.0.4"
gast = ">=0.5.4"
numpy = ">=1.26.3"
nbval = ">=0.10.0"
scipy = ">=1.11.4"
pytest = ">=7.4.4"
pytest-cov = ">=4.1.0"
coverage = ">=7.4.0"
black = ">=24.3.0"
mpi4py = ">=3.1.5"
pip = ">=23.3.2"
numba = ">=0.58.1"
cython = ">=3.0.7"
pythran = ">=0.15.0"

[build-dependencies]
pdm-backend = ">=2.1.8"

[pypi-dependencies]
pytest-venv = "*"
