
channels:
  - conda-forge

dependencies:
  - python=3.6
  - ipython
  - jupyter
  - pip:
    - sphinx_rtd_theme
    - sphinx
    - numpydoc
    - fluiddyn
    - gast
    - git+https://github.com/serge-sans-paille/beniget#egg=beniget
